version: '3'
services:
  frontend:
    build: ./
    working_dir: /usr/src/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/usr/src/app
    expose:
      - "8081"
    command: "npm start"